### ISSUE TITLE
trying fas::Float<int64_t, int16_t> issues

### ISSUE THREAD

**Issue by rforcen** [clemensmanert/fas#1]
when trying the type 

fas::Float<int64_t, int16_t>a(1), b(0.45), p; // 64 bit mantissa, 16 bit exponent
p=a*b;

i get 0 as result, why?

works fine with  fas::Float<int32_t, int16_t>

g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
g++ -std=c++2a

**Comment by clemensmanert** [comment]
Thanks a lot for bug-report. I wrote you an email.

The multiplication does not work with `1` and I forgot to check both factors. I fixed it in the commit [980090c](https://github.com/clemensmanert/fas/commit/980090ca0ff7b85b8b91208da97b21227438a062).

**Comment by rforcen** [comment]
thanks a lot i'll give it a run,
best
bob
